# Generated by Django 4.2.3 on 2023-07-06 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_rename_merchant_id_order_payment_intent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-created_at',)},
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
